parameters:

services:
    braincrafted_bootstrap.twig.icon_extension:
        class: Braincrafted\Bundle\BootstrapBundle\Twig\BootstrapIconExtension
        tags:
            - { name: twig.extension }
    braincrafted_bootstrap.twig.label_extension:
        class: Braincrafted\Bundle\BootstrapBundle\Twig\BootstrapLabelExtension
        tags:
            - { name: twig.extension }
    braincrafted_bootstrap.twig.badge_extension:
        class: Braincrafted\Bundle\BootstrapBundle\Twig\BootstrapBadgeExtension
        tags:
            - { name: twig.extension }
    braincrafted_bootstrap.twig.form_extension:
        class: Braincrafted\Bundle\BootstrapBundle\Twig\BootstrapFormExtension
        tags:
            - { name: twig.extension }

    braincrafted_bootstrap.flash:
        class: Braincrafted\Bundle\BootstrapBundle\Session\FlashMessage
        arguments:
            - @session

    braincrafted_bootstrap.form.type.collection:
        class: Braincrafted\Bundle\BootstrapBundle\Form\Type\BootstrapCollectionType
        tags:
            - { name: form.type, alias: braincrafted_collection }

    braincrafted_bootstrap.form.type.money:
        class: Braincrafted\Bundle\BootstrapBundle\Form\Type\MoneyType
        tags:
            - { name: form.type, alias: money }

    braincrafted_bootstrap.form.extension.typesetter_extension:
        class: Braincrafted\Bundle\BootstrapBundle\Form\Extension\TypeSetterExtension
        tags:
            - { name: form.type_extension, alias: form }

